import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: {
      ...StyleSheet.absoluteFillObject,
      justifyContent: "flex-end",
      alignItems: "center",
    },
    radiusControl: {
      position: "absolute",
      top: 120,
      left: 10,
      right: 10,
      backgroundColor: "white",
      borderRadius: 15,
      padding: 15,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    radiusText: {
      fontSize: 16,
      fontWeight: "bold",
      marginBottom: 10,
      textAlign: "center",
      color: "#1E88E5", // Blue color for the text
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
      backgroundColor: '#f5f5f5',
    },
    loadingText: {
      marginTop: 10,
      fontSize: 16,
      color: '#333',
    },
    slider: {
      width: "100%",
    },
    markerImage: {
      width: 50,
      height: 50,
      resizeMode: "contain",
    },
    radiusControl: {
      position: "absolute",
      top: 120,
      left: 10,
      right: 10,
      backgroundColor: "white",
      borderRadius: 15,
      padding: 15,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    radiusText: {
      fontSize: 16,
      fontWeight: "bold",
      marginBottom: 10,
      textAlign: "center",
    },
    slider: {
      width: "100%",
    },
    autocompleteInput: {
      height: 50,
      borderRadius: 25,
      paddingHorizontal: 20,
      fontSize: 16,
      backgroundColor: "white",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    infoCard: {
      position: "absolute",
      bottom: 20,
      left: 20,
      right: 20,
      backgroundColor: "white",
      borderRadius: 15,
      padding: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    infoButton: {
      backgroundColor: "#1E88E5",
      paddingVertical: 12,
      paddingHorizontal: 25,
      borderRadius: 25,
      alignSelf: "center",
      marginTop: 10,
    },
    infoButtonText: {
      color: "white",
      fontSize: 16,
      fontWeight: "bold",
    },
    map: {
      ...StyleSheet.absoluteFillObject,
    },
    autocompleteContainer: {
      position: "absolute",
      top: 50,
      left: 10,
      right: 10,
      zIndex: 1,
    },
    autocompleteInput: {
      height: 50,
      borderRadius: 25,
      paddingHorizontal: 20,
      fontSize: 16,
      backgroundColor: "white",
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    infoCard: {
      position: "absolute",
      bottom: 20,
      left: 20,
      right: 20,
      backgroundColor: "white",
      borderRadius: 15,
      padding: 20,
      shadowColor: "#000",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.25,
      shadowRadius: 3.84,
      elevation: 5,
    },
    infoTitle: {
      fontSize: 18,
      fontWeight: "bold",
      marginBottom: 10,
    },
    infoDistance: {
      fontSize: 16,
      color: "#666",
      marginBottom: 15,
    },
    infoButton: {
      backgroundColor: "#1E88E5",
      paddingVertical: 10,
      paddingHorizontal: 20,
      borderRadius: 25,
      alignSelf: "flex-start",
    },
    infoButtonText: {
      color: "white",
      fontSize: 16,
      fontWeight: "bold",
    },
  });